package com.woodworkingexchange.domain;

// Generated Mar 25, 2012 11:08:03 AM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.springframework.security.core.GrantedAuthority;

/**
 * Authorities generated by hbm2java
 */
@Entity
@Table(name = "authorities")
public class Authorities implements java.io.Serializable, GrantedAuthority
{
  private static final long serialVersionUID = -8109390932709442980L;
  private Integer id;
  private Users users;
  private String authority;

  public Authorities()
  {
  }

  public Authorities(Users users, String authority)
  {
    this.users = users;
    this.authority = authority;
  }

  @Id
  @GeneratedValue(strategy = IDENTITY)
  @Column(name = "id", unique = true, nullable = false)
  public Integer getId()
  {
    return this.id;
  }

  public void setId(Integer id)
  {
    this.id = id;
  }

  @ManyToOne
  @JoinColumn(name = "user_id", nullable = false)
  public Users getUsers()
  {
    return this.users;
  }

  public void setUsers(Users users)
  {
    this.users = users;
  }

  @Column(name = "authority", nullable = false, length = 50)
  public String getAuthority()
  {
    return this.authority;
  }

  public void setAuthority(String authority)
  {
    this.authority = authority;
  }

}
